name: SMARTVATS YASPEECHKIT-WRAPPER deploy scripts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, solutionpoint]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Remove Python Files
      run: |
        find /srv/scripts/asterisk-backend/app ! -name '.settings.json' -type f -delete

    - name: Copy Scripts to Local Directory
      run: |
        cp -r app/* /srv/scripts/asterisk-backend/app

    - name: Restart asterisk-backend container
      run: |
        cd /srv
        docker-compose restart asterisk-backend
